# Generated by Django 2.2.12 on 2020-06-01 14:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Indagine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titoloIndagine', models.CharField(max_length=20)),
                ('erogatore', models.CharField(max_length=20)),
                ('imgUrl', models.FileField(upload_to='media/')),
                ('tematica', models.TextField()),
            ],
            options={
                'verbose_name': 'Indagine',
                'verbose_name_plural': 'Indagini',
            },
        ),
        migrations.CreateModel(
            name='Utente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
            ],
            options={
                'verbose_name': 'Utente',
                'verbose_name_plural': 'Utenti',
            },
        ),
        migrations.CreateModel(
            name='Questionario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titolo', models.CharField(max_length=20)),
                ('qualtricsUrl', models.CharField(max_length=250)),
                ('compilato', models.BooleanField()),
                ('indagine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questionari', to='BICAPweb.Indagine')),
            ],
            options={
                'verbose_name': 'Questionario',
                'verbose_name_plural': 'Questionari',
            },
        ),
        migrations.CreateModel(
            name='Informazione',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomeFile', models.CharField(max_length=20)),
                ('fileUrl', models.FileField(upload_to='media/')),
                ('thumbnailUrl', models.FileField(upload_to='media/')),
                ('tipoFile', models.CharField(max_length=20)),
                ('questionario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='informazioni', to='BICAPweb.Questionario')),
            ],
            options={
                'verbose_name': 'Informazione',
                'verbose_name_plural': 'Informazioni',
            },
        ),
        migrations.CreateModel(
            name='Distribuzione',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('terminata', models.BooleanField()),
                ('indagine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='distribuzioni', to='BICAPweb.Indagine')),
                ('utente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='distribuzioni', to='BICAPweb.Utente')),
            ],
            options={
                'verbose_name': 'Distribuzione',
                'verbose_name_plural': 'Distribuzioni',
            },
        ),
    ]
