# Generated by Django 2.2.12 on 2020-06-02 14:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BICAPweb', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='informazione',
            options={},
        ),
        migrations.RemoveField(
            model_name='informazione',
            name='questionario',
        ),
        migrations.AlterField(
            model_name='distribuzione',
            name='indagine',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='utenti', to='BICAPweb.Indagine'),
        ),
        migrations.AlterField(
            model_name='distribuzione',
            name='utente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='indagini', to='BICAPweb.Utente'),
        ),
        migrations.AlterField(
            model_name='indagine',
            name='imgUrl',
            field=models.FileField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='informazione',
            name='fileUrl',
            field=models.FileField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='informazione',
            name='thumbnailUrl',
            field=models.FileField(upload_to=''),
        ),
        migrations.CreateModel(
            name='InformazioneQuestionario',
            fields=[
                ('informazione_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='BICAPweb.Informazione')),
                ('questionario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='informazioni', to='BICAPweb.Questionario')),
            ],
            options={
                'verbose_name': 'Informazione Questionario',
                'verbose_name_plural': 'Informazioni Questionari',
            },
            bases=('BICAPweb.informazione',),
        ),
        migrations.CreateModel(
            name='InformazioneIndagine',
            fields=[
                ('informazione_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='BICAPweb.Informazione')),
                ('questionario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='informazioni', to='BICAPweb.Indagine')),
            ],
            options={
                'verbose_name': 'Informazione Indagine',
                'verbose_name_plural': 'Informazioni Indagini',
            },
            bases=('BICAPweb.informazione',),
        ),
    ]
