# Generated by Django 3.0.7 on 2020-06-08 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BICAPweb', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='informazione',
            name='fileUrl',
            field=models.ImageField(upload_to=''),
        ),
    ]
