# Generated by Django 3.0.7 on 2020-06-09 07:20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('BICAPweb', '0002_auto_20200608_1627'),
    ]

    operations = [
        migrations.AddField(
            model_name='indagine',
            name='ultimaModifica',
            field=models.TimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='informazione',
            name='ultimaModifica',
            field=models.TimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='indagine',
            name='imgUrl',
            field=models.ImageField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='informazione',
            name='fileUrl',
            field=models.FileField(upload_to=''),
        ),
    ]
