# Generated by Django 2.2.12 on 2020-06-03 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BICAPweb', '0002_auto_20200602_1609'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gruppo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name': 'Gruppo',
                'verbose_name_plural': 'Gruppi',
            },
        ),
        migrations.AddField(
            model_name='utente',
            name='gruppi',
            field=models.ManyToManyField(to='BICAPweb.Gruppo'),
        ),
    ]
