# Generated by Django 2.2.13 on 2020-06-03 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BICAPweb', '0003_auto_20200603_1410'),
    ]

    operations = [
        migrations.AddField(
            model_name='indagine',
            name='gruppi',
            field=models.ManyToManyField(related_name='gruppi_interessati', to='BICAPweb.Gruppo'),
        ),
        migrations.AlterField(
            model_name='utente',
            name='gruppi',
            field=models.ManyToManyField(related_name='gruppi', to='BICAPweb.Gruppo'),
        ),
    ]
